// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ERQ5clfqqg6lRYy4hAxik7YIGu9kMYI',
    appId: '1:411338240010:web:6cb3d976fface2e3e6aff3',
    messagingSenderId: '411338240010',
    projectId: 'voters-list-39703',
    authDomain: 'voters-list-39703.firebaseapp.com',
    storageBucket: 'voters-list-39703.appspot.com',
    measurementId: 'G-LZQRXXBRLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI391XCipHydC6pCyw-ZvZ3GmQH9TlVg8',
    appId: '1:411338240010:android:eef6a3a3a488e38be6aff3',
    messagingSenderId: '411338240010',
    projectId: 'voters-list-39703',
    storageBucket: 'voters-list-39703.appspot.com',
  );
}
